### ISSUE TITLE
[Bug]: coupons:crafting_coupon return the whole slot ingredient

### ISSUE THREAD

**Issue by 2929762171** [Mrbysco/Coupons#1]
### General Info

- [ ] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

36.2.39

### Minecraft version

1.16.5

### Mod version

Coupons-1.16.3-1.0.0

### Java version

8_331

### Issue Description

64+1+1+1+1+1+1+1+1 ingot
=63*ingot(crafting table)+64*ingot(return inventory)+1*block

consume 1* crafting_coupon

**Comment by Mrbysco** [comment]
? What recipe are you even talking about

**Comment by 2929762171** [comment]
You can try iron ingot, everything.

**Comment by ShyNieke** [comment]
can you please provide screenshots or a video explaining the issue as we have no idea what the issue is here

**Comment by 2929762171** [comment]
.

**Comment by 2929762171** [comment]
Well I don't know how to provide a screenshot, please try this in crafting table when you have one crafting_coupon:
64*iron_ingot+1*iron_ingot+1*iron_ingot
+1*iron_ingot+1*iron_ingot+1*iron_ingot
+1*iron_ingot+1*iron_ingot+1*iron_ingot

On my side, I'll get 64 iron ingot and 1 iron block in my inventory, and 63 iron ingot still on crafting table. it means one coupon can get 64 ingredient back.

Every recipes can do this.

**Comment by Mrbysco** [comment]
I'll look into it tomorrow as it's currently late for me
